### ISSUE TITLE
diagram construct error：TypeError: '<' not supported between instances of 'Node' and 'Node'

### ISSUE THREAD

**Issue by wzx-ziron** [lycantropos/voronoi#1]
This is my code for test ，and it gives me this error，what can I do to fix this？
```diagram = Diagram()
diagram.construct([],[])
diagram.construct([Point(0, 0), Point(4, 0), Point(4, 4), Point(0, 4)], [])
print(diagram.vertices)```
```
_heappush(self._items, (self._sorting_key(value), value))
TypeError: '<' not supported between instances of 'Node' and 'Node'
```

**Comment by lycantropos** [comment]
thanks for the report, I'm able to reproduce it, the problem lies within `prioq` library, going to fix it today

as a temporal fix you can run
```python
python -m pip --force-reinstall 'prioq<0.5'
```
after installation of `voronoi`

**Comment by lycantropos** [comment]
also, newer version with a fix will support only `Python3.7+` since `Python3.6` reached EOL and I'm also not interested in supporting it

**Comment by lycantropos** [comment]
found some unrelated but nasty bugs, took more time to fix than expected, should work now (since version [`0.4.0`](pypi.org/project/voronoi/0.4.0)), thanks again for your contribution
