### ISSUE TITLE
How can I get medial axis to simplify a rectilinear polygon?

### ISSUE THREAD

**Issue by wzx-ziron** [lycantropos/voronoi#2]
Thanks for last question, it works now. But the reason I use voronoi is to get the medial axis inside a single polygon so I can simplify the polygon just like the picture below.  I'm a beginner at this. So  I wonder if there exist a function or something that's able to generate the medial axis, or can I do a post-process using the diagram.vertices...etc to generate it myself?
![image](https://user-images.githubusercontent.com/59268294/233258345-c32abba9-8903-41df-a47e-87c6442ddc57.png)

**Comment by wzx-ziron** [comment]
I've learning voronoi diagram recently. Actually I need to generate the voronoi diagram like the picture shows and then the diagram.edges are what I want. But I don't want the edges to be curves and I think it's related to the type of metric that being used. As the picture shows, using L∞ metric will generate only lines, so is this metric supported?
![image](https://user-images.githubusercontent.com/59268294/233580842-d72d7b12-570c-4f49-a034-22d85fcda5a2.png)

**Comment by lycantropos** [comment]
No, it is a port of [boost/voronoi](https://github.com/boostorg/polygon), which works with euclidean distance, but you can potentially fork and change it to a metric that you need, but I guess it won't be easy since you need to rewrite an algorithm according to it

**Comment by wzx-ziron** [comment]
Thanks for anwering. By the way, I've found the original paper. Hope I can implement it.
